// Auto-generated by Mavis daemon — do not edit
export { default } from "C:\\Users\\jethr\\AppData\\Local\\Programs\\MiniMax Code\\resources\\resources\\daemon\\node_modules\\@mavis\\opencode-skill-tool\\ask-user-tool.js"
